<a href="https://colab.research.google.com/github/anhtran123-max/practice_python/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3]) # T⁄o array 1 chi•u
print(type(a)) # Prints "<class 'numpy.ndarray'>"
print(a.shape) # Prints "(3,)"
print(a[0], a[1], a[2]) # Prints "1 2 3"
a[0] = 5 # Thay đŒi phƒn tß vị tr‰ sŁ 0
print(a) #Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]]) # T⁄o array 2 chi•u
print(b.shape) # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) # Prints "1 2 4"

(2, 3)
1 2 4


In [4]:
a = np.zeros((2,2)) # T⁄o array với t§t c£ c¡c phƒn tß 0
print(a) # Prints "[[ 0. 0.]

[[0. 0.]
 [0. 0.]]


In [5]:
b = np.ones((1,2)) # T⁄o array với c¡c phƒn tł 1
print(b) # Prints "[[ 1. 1.]]"

[[1. 1.]]


In [6]:
c = np.full((2,2), 7) # T⁄o array với c¡c phƒn tß 7
print(c) # Prints "[[ 7. 7.]

[[7 7]
 [7 7]]


In [7]:
d = np.eye(2) # T⁄o identity matrix k‰ch thước 2*2
print(d) # Prints "[[ 1. 0.]

[[1. 0.]
 [0. 1.]]


In [8]:
e = np.random.random((2,2)) # T⁄o array với c¡c phƒn tß đưæc t⁄o ng¤u nhi¶n
print(e) # Might print "[[ 0.91940167 0.08143941]

[[0.92664509 0.58500438]
 [0.48082358 0.48517519]]


## Array indexing
Tương tự như list, numpy array cũng có thể slice. Tuy nhiên vì numpy array có nhiều chiều, nên khi dùng slice phải chỉ định rõ chiều nào.

In [9]:
import numpy as np

In [10]:
# T⁄o array 2 chi•u với k‰ch thước (3, 4)
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [11]:
# Dùng slide đ” lấy ra subarray gồm 2 hàng đầu tiên (1 & 2) và 2 cột (2 & 3).
# Output là array kích thước 2*2
# [[2 3]
# [6 7]]
b = a[:2, 1:3]

In [12]:
print(a[0, 1]) # Prints "2"
a[0, 1] = 77 # Ch¿nh sßa phƒn tß trong array
print(a[0, 1]) # Prints "77

2
77


In [13]:
# T⁄o array 2 chi•u k‰ch thước (3, 4)
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [14]:
row_r1 = a[1, :] # L§y ra hàng thø 2 trong a, output array 1 chi•u
row_r2 = a[1:2, :] # L§y ra hàng thø 1&2 trong a, output array 2 chi•u
print(row_r1, row_r1.shape) # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [15]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# T‰nh tŒng
# [[ 6.0 8.0]
# [10.0 12.0]]
print(x + y)
print(np.add(x, y))
# Ph†p trł
# [[-4.0 -4.0]
# [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))
# Ph†p nh¥n element-wise
# [[ 5.0 12.0]
# [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
# Ph†p chia element-wise
# [[ 0.2 0.33333333]
# [ 0.42857143 0.5 ]]
print(x / y)
print(np.divide(x, y))
# T‰nh c«n b“c hai
# [[ 1. 1.41421356]
# [ 1.73205081 2. ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [16]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
# Nh¥n ma tr“n, output sŁ 219
print(v.dot(w))
print(np.dot(v, w))
# Nh¥n ma tr“n; output ma tr“n 2*2
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [17]:
x = np.array([[1,2],[3,4]])
print(np.sum(x)) # T‰nh tŒng t§t c£ phƒn tß trong array; prints "10"
print(np.sum(x, axis=0)) # T‰nh tŒng phƒn tß mØi hàng; prints "[4 6]"
print(np.sum(x, axis=1)) # T‰nh tŒng

10
[4 6]
[3 7]


## Broadcasting
Broadcasting là một kĩ thuật cho phép numpy làm việc với các array có shape khác nhau khi thực
hiện các phép toán.

In [18]:
import numpy as np

In [20]:
# Cºng vector v với mØi hàng cıa ma tr“n x, k‚t qu£ lưu ở ma tr“n y.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # T⁄o 1 array có chi•u giŁng x
# Dùng loop đ” vector v với mØi hàng cıa ma tr“n
for i in range(4):
  y[i, :] = x[i, :] + v
print(y)
# K‚t qu£ cıa y
# [[ 2 2 4]
# [ 5 5 7]
# [ 8 8 10]
# [11 11 13]]
# Cºng ki”u broadcasting trong python
print(x + v)
# K‚t qu£
# [[ 2 2 4]
# [ 5 5 7]
# [ 8 8 10]
# [11 11 13]]
# 2 k‚t qu£ cho ra giŁng nhau

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
