<a href="https://colab.research.google.com/github/anhtran123-max/practice_python/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3]) # Tạo array 1 chi•u
print(type(a)) # Prints "<class 'numpy.ndarray'>"
print(a.shape) # Prints "(3,)"
print(a[0], a[1], a[2]) # Prints "1 2 3"
a[0] = 5 # Thay đổi phần tử vị trí số 0
print(a) #Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]]) # Tạo array 2 chiều
print(b.shape) # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) # Prints "1 2 4"

(2, 3)
1 2 4


In [ ]:
a = np.zeros((2,2)) # Tạio array với tất cả các phần tử 0
print(a) # Prints "[[ 0. 0.]

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2)) # Tạo array với các phần tử 1
print(b) # Prints "[[ 1. 1.]]"

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Tạo array với các phần tử 7
print(c) # Prints "[[ 7. 7.]

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2) # Tạo identity matrix kích thước 2*2
print(d) # Prints "[[ 1. 0.]

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) # Tạo array với các phần tử được tạo ngẫu nhiên
print(e) # Might print "[[ 0.91940167 0.08143941]

[[0.92664509 0.58500438]
 [0.48082358 0.48517519]]


## Array indexing
Tương tự như list, numpy array cũng có thể slice. Tuy nhiên vì numpy array có nhiều chiều, nên khi dùng slice phải chỉ định rõ chiều nào.

In [ ]:
import numpy as np

In [ ]:
# Tạo array 2 chiều với kích thước (3, 4)
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
# Dùng slide để lấy ra subarray gồm 2 hàng đầu tiên (1 & 2) và 2 cột (2 & 3).
# Output là array kích thước 2*2
# [[2 3]
# [6 7]]
b = a[:2, 1:3]

In [ ]:
print(a[0, 1]) # Prints "2"
a[0, 1] = 77 # Chỉnh sửa phần tử trong array
print(a[0, 1]) # Prints "77

2
77


In [ ]:
# Tạo array 2 chiều kích thước (3, 4)
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
row_r1 = a[1, :] # Lấy ra hàng thứ 2 trong a, output array 1 chi•u
row_r2 = a[1:2, :] # Lấy ra hàng thứ 1&2 trong a, output array 2 chi•u
print(row_r1, row_r1.shape) # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Tính tổng
# [[ 6.0 8.0]
# [10.0 12.0]]
print(x + y)
print(np.add(x, y))
# Phép trừ
# [[-4.0 -4.0]
# [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))
# Phép nhân element-wise
# [[ 5.0 12.0]
# [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
# Phép chia element-wise
# [[ 0.2 0.33333333]
# [ 0.42857143 0.5 ]]
print(x / y)
print(np.divide(x, y))
# Tính căn bậc hai
# [[ 1. 1.41421356]
# [ 1.73205081 2. ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
# Nhân ma trận, output số 219
print(v.dot(w))
print(np.dot(v, w))
# Nhân ma trận; output ma trận 2*2
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2],[3,4]])
print(np.sum(x)) # Tính tổng tất cả các phần tử trong array; prints "10"
print(np.sum(x, axis=0)) # Tính tổng phần tử mỗi hàng; prints "[4 6]"
print(np.sum(x, axis=1)) # Tính tổng

10
[4 6]
[3 7]


## Broadcasting
Broadcasting là một kĩ thuật cho phép numpy làm việc với các array có shape khác nhau khi thực
hiện các phép toán.

In [ ]:
import numpy as np

In [ ]:
# Cộng vector v với mọi hàng của ma trận x, kết quả lưu ở ma trận y.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # Tạo 1 array có chiều giống x
# Dùng loop để vector v với mỗi hàng của ma trận
for i in range(4):
  y[i, :] = x[i, :] + v
print(y)
# Kết quả của y
# [[ 2 2 4]
# [ 5 5 7]
# [ 8 8 10]
# [11 11 13]]
# Cộng kiểu broadcasting trong python
print(x + v)
# Két quả
# [[ 2 2 4]
# [ 5 5 7]
# [ 8 8 10]
# [11 11 13]]
# 2 kết quả cho ra giống nhau

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
